name: Build Kernel Feisty
on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'true'
        path: kernel
    - name: Prepare ccache timestamp
      id: ccache_cache_timestamp
      shell: cmake -P {0}
      run: |
        string(TIMESTAMP current_date "%Y-%m-%d-%H;%M;%S" UTC)
        message("::set-output name=timestamp::${current_date}")
    - name: ccache
      uses: actions/cache@v1
      env:
        cache-name: ccache
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.ccache
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${ { steps.ccache_cache_timestamp.outputs.timestamp } }
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-${ { steps.ccache_cache_timestamp.outputs.timestamp } }
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Build With Shell
      run: |
        bash kernel/build-cbl.sh
    - name : Upload zip package
      uses: actions/upload-artifact@master
      with:
        path: kernel/AnyKernel3
        name: Feisty
